name: CI - tests & quality
on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system deps (for Linux builds)
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Install pip + wheel
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint (flake8)
        run: pip install flake8 && flake8 .

      - name: Type checks (mypy)
        run: pip install mypy && mypy .

      - name: Security check (pip-audit)
        run: pip install pip-audit && pip-audit --progress

      - name: Run tests (pytest)
        run: pip install pytest pytest-asyncio && pytest -q

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./tests/reports || ./test-results || .
